version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - backend-data:/app/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:

